### ISSUE TITLE
Add view for zero donations

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#142]
When there are no donations in any year for a donor, as special view should be shown.
<img width="1512" alt="Donations" src="https://user-images.githubusercontent.com/693641/161517796-e72d736a-f0f6-4c09-abfc-cd5034d26e1b.png">
<img width="375" alt="Donations Mobile Zero" src="https://user-images.githubusercontent.com/693641/161517811-99fa35ef-eceb-43b8-8620-3775b376474e.png">

**Comment by JorgenLjones** [comment]
@fellmirr , what's the status on this functionality?
