### ISSUE TITLE
The floating Gi-button - donations link can semantically be an <a> tag indside an <aside>

### ISSUE THREAD

**Issue by HEYROCKME** [stiftelsen-effekt/main-site#195]
In our endavour to comply with  WCAG standards, we have to be aware that divs alone don't give "context" to screen readers.

This can of course be handle with an aria-label, but a more semantically correct approach might be using an <aside>outside of the <main> element since the role of the "link" is not strictly related to the content of the homepage.

**Comment by fellmirr** [comment]
Linking this issue to #296, do them in tandem.
