### ISSUE TITLE
Remove Konduit and gieffektivt.no titles

### ISSUE THREAD

**Issue by philiphand** [stiftelsen-effekt/main-site#303]
- [ ] Auth0
  - [x] Create new tenant
  - [x] Migrate applications, rules and actions
  - [ ] Migrate users
    - [x] Send support ticket for password hashes and salts
    - [ ] Import users to new tenant
  - [ ] Change backend check from konduit-user-id to gieffektivt-user-id
  - [ ] Test new applications locally
  - [ ] Switch prod application client ids and secrets etc...
    - [ ] Update google cloud secrets
  - [ ] Test
    - [ ] Profile page
    - [ ] Admin panel
    - [ ] Scheduled routines
    - [ ] Swagger
- [x] Sanity
  - [x] Update default studio URL
  - [x] Update CORS policies as needed
- [ ] Website
  - [x] Update title on profile page
  - [ ] Update all client side calls to use gieffektivt-user-id
  - [x] Change readme and package.json
- [ ] AvtaleGiro i nettbank
- [x] Vipps recurring

**Comment by JorgenLjones** [comment]
Sanity Studio domain, for reference
![Image](https://user-images.githubusercontent.com/12774906/179767388-2c2b0225-115b-4a78-b628-814715bf7657.png)

**Comment by JorgenLjones** [comment]
Tab title when logged into Min Side, for reference

![Image](https://user-images.githubusercontent.com/12774906/180014500-a2a43648-6a59-4658-9c40-730747feffa7.png)

**Comment by philiphand** [comment]
Continued in issue #363
