### ISSUE TITLE
Next button way to small in widget

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#326]
The next button is way to small in the widget (along with other buttons in same place). Change probably happened in relation to tab / accesibility changes. It must be scaled up (a modified EffektButton).

![Image](https://user-images.githubusercontent.com/693641/179781015-8f4672e1-9df1-40d9-a9d4-ec056c10e05d.png)

**Comment by philiphand** [comment]
Use styled-components on EffektButton to overwrite size

**Comment by fellmirr** [comment]
@philiphand 

`components/main/widget/components/shared/Buttons/NavigationButtons.style.tsx`

Her kan du se hvordan det er gjort med navigation buttons.

Her er et utsnitt fra referansedesignet fra mobil. Lurer på om det er noe kode i cssen som gjør de litt mindre på desktop :)

![Image](https://user-images.githubusercontent.com/693641/179948922-b92cdb26-bf56-4ff0-9597-757477d2abeb.png)
