### ISSUE TITLE
FB donation tax registration form is missing on new site

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#349]

**Comment by JorgenLjones** [comment]
We want to add this to Min Side. Håkon sketch up a new tab for it there.
We must also add a section to /skattefradrag with info and instructions to log into Min Side + an anchor link where to redirect /fb-skattefradrag. Jørgen will write the new text when the form works on Min Side

**Comment by philiphand** [comment]
@fellmirr Where can I find the sketch?

**Comment by philiphand** [comment]
Add a new link in the Navbar menu
