### ISSUE TITLE
[Await pushing to Master] Add a notification on Min Side for donors who have an active AG or Vipps rec to SCI

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#380]
First make a quick query to make sure there exist active AG or Vipps rec to SCI. If this number is below four people - don't bother doing this issue.

Notification text:
> Du har en aktiv donasjonsavtale gjennom [AvtaleGiro/Vipps fast betaling] til SCI Foundation. Vi anbefaler ikke lenger donasjoner til SCI Foundation gjeldende fra 18.08.22 og vil slutte å tildele penger til dem 31. oktober 2022. Les mer om denne endringen på [bloggen vår](https://github.com/orgs/stiftelsen-effekt/projects/9/views/www.gieffektivt.no/articles/nye-evalueringskriterier-for-topplista).
> Donasjoner øremerket SCI Foundation blir fra og med 1. november 2022 i stedet følge [Smart fordeling](https://gieffektivt.no/smart-fordeling). Om du ønsker en annen fordeling kan du gå inn på [Avtaler](https://gieffektivt.no/profile/agreements) og oppdatere fordelingen på din faste donasjon, eller fylle ut donasjonsskjemaet for en ny donasjon. Ta kontakt om du har noen spørsmål.

**Comment by fellmirr** [comment]
#385
