### ISSUE TITLE
Hide name and email fields in FB-tax form and make SSN/OrgNr a drop down

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#389]
EDIT: 
- [x] Hide name and email SSN/OrgNr and fetch these from the SSN/OrgNr. 
- [x] Convert SSN/OrgNr to a drop down of registered tax units, 
- [x] Default SSN/OrgNr to the first SSN registered.
- [x] Add option to add a new one (for some other tax unit) if you want

Email must be known at this stage, and Name and SSN can be known. Fill those automatically.
![Image](https://user-images.githubusercontent.com/12774906/185917992-8e0365e5-bee2-4d24-98a3-8aff558406e2.png)

**Comment by fellmirr** [comment]
@JorgenLjones Name and email are prefilled? Not sure why it wouldn't be filled in your case.

SSN is not filled intentionally, given that we are soon differentiating on tax units. Makes sense? There could be many different tax units / ssn, and we also want the donor to actively decide which tax unit the donation should be ascribed too, right?

**Comment by JorgenLjones** [comment]
Hm, I'll have to think about this. It seems kinda clunky now. I want less unnecessary information and fields that don't need to be filled

Maybe it's better that the name and email field is completely hidden and that you just add SSN/ORGNR from a list of the tax units you've registered under Profile?

**Comment by fellmirr** [comment]
Yes, that seems better. And an option to add a new one if you want.

**Comment by JorgenLjones** [comment]
@EliseAndresen are all goals of this issue completed or obsolete?

**Comment by EliseAndresen** [comment]
All but one are completed/obsolete.  Default SSN/OrgNr to the first SSN registered is stil not implemented.
