### ISSUE TITLE
☆ Expand on Facebook tax registration details

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#390]
![Image](https://user-images.githubusercontent.com/12774906/185920479-5ce0027d-0012-4792-b896-9f2a5f8f91e0.png)

**Comment by EliseAndresen** [comment]
If easy to fix, make functionality to prevent word break in numbers. If not add as separate issue.

**Comment by EliseAndresen** [comment]
This will be fixed by #400
