### ISSUE TITLE
Preview in Santy crash when adding item

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#407]
Feature that breaks preview:

![Image](https://user-images.githubusercontent.com/12774906/182682191-7fbe69eb-d8ba-4b02-99fd-51e7fe7a6db7.png)

Error message:

![Image](https://user-images.githubusercontent.com/12774906/182682114-3296fa19-b24e-4f8e-b18a-720602bd9a65.png)

**Comment by karirk** [comment]
Ny versjon av Sanity.
