### ISSUE TITLE
Better user experience when signing up with an existing email

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#452]
Right now, if you attempt to sign up with an email already associated with a user, you get a generic "something went wrong" message.

We should send the user an email informing them that they already have a user, and that they can log in with that.

![Image](https://user-images.githubusercontent.com/693641/195071366-3fccac87-9f5e-4d90-b049-d46b77975352.png)

**Comment by EliseAndresen** [comment]
Reviewed options and concluded with this:

We want to set up a flow that gives the same result when you register with an unused email and with a previously registered one. The user gets a message about needing to verify their account, and we send out an email to the user in both scenarios. If the user already has an account we ask them to log in or reset their password, and if it is a new user we ask them to verify the account.

We do not want to inform the user of the email already being in use in the registration form as this could pose a small security risk.
