### ISSUE TITLE
Impact estimates: Add expandable menu for yearly aggregates

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#475]
https://github.com/stiftelsen-effekt/main-site/pull/417#issuecomment-1269498531

![Image](https://user-images.githubusercontent.com/693641/196113638-7c5d640c-4a9b-4e18-a249-a75d953caf93.png)

**Comment by EliseAndresen** [comment]
[Figma design ](https://www.figma.com/file/rxgTB6O7vQZWbKDSoUY6EU/Min-Side?node-id=1397%3A3170&t=Z1CUBJU7ga75aA9q-1)
