### ISSUE TITLE
Tax units: Create tax units table

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#480]
![Image](https://user-images.githubusercontent.com/693641/196117502-70dcdf4f-9974-4454-9216-99791aae4f43.png)

These should be basically available in the backend, on some of the `/tax/` endpoints. Might need to update the backend to include a check user check (as opposed to just an admin check which I suspect is the case now). See similar usage of checkUser (or something like that) on other endpoints, such as /donors/:id/donations f.ex.

**Comment by EliseAndresen** [comment]
What happens when there are no tax units?
 Missing tax deductions summation for given year (or all time?)

**Comment by EliseAndresen** [comment]
New text for when there is are no tax units:
"Vi har ikke registrert noen skatteenheter på deg. For å få skattefradrag på donasjoner må du registrere ditt personnummer, eller organisasjonsnummer hvis du donerer fra en skattepliktig bedrift. Du kan registrere flere skatteenheter på samme bruker."



![Image](https://user-images.githubusercontent.com/112557835/197554734-a5ee0cdd-eaf5-419d-9875-28a051ac3b03.png)
