### ISSUE TITLE
Tax units: Update agreement editing to respect tax units and smart distribution (standard distribution)

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#484]
Currently, when editing agreements we ignore the smart distribution / standard distribution flag, and simply carry over the tax unit (if there is any) on the agreement. There has been done quite a bit of work on this issue in the branch for AG editing in admin panel, which should be useful.

https://github.com/stiftelsen-effekt/effekt-admin/issues/279

![Image](https://user-images.githubusercontent.com/693641/196120227-cb3ce3c3-f489-406b-85ec-4dbe08663d0b.png)

**Comment by EliseAndresen** [comment]
![image](https://user-images.githubusercontent.com/112557835/198281998-8a466f1a-7877-460d-939a-5494052a519e.png)

Design for distribution selector button/dropdown
