### ISSUE TITLE
Create a solution for anon vipps agreements

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#485]
Figure out how we should accommodate anonymous vipps agreements. They can't log in to min side, so how do they cancel / edit their agreements?

**Comment by JorgenLjones** [comment]
Also see https://github.com/stiftelsen-effekt/main-site/issues/451

**Comment by philiphand** [comment]
Subtasks
- [ ] Simplify uuid generation (the current hash code is unnecessary)
- [ ] Read URL and find agreement code
- [ ] Find donor from agreement URL code
- [ ] Check if donor is anon
- [ ] Create front-end for editing Vipps agreements anonymously without login
