### ISSUE TITLE
Hover on "Min side" in menu shows small line on each side of the button

### ISSUE THREAD

**Issue by EliseAndresen** [stiftelsen-effekt/main-site#504]
![Image](https://user-images.githubusercontent.com/112557835/199028918-0139d9d6-e5d1-44a1-b963-46a577d0d45b.png)

Looks like there is a global border bottom property for a elements that triggers it.

![Image](https://user-images.githubusercontent.com/112557835/199029365-ead6151d-44b6-4f40-8437-eea5dbabf9c7.png)

**Comment by fellmirr** [comment]
This seems to be fixed.
