### ISSUE TITLE
Add a tag in links to articles in the articles page to prevent them being viewed as orphaned pages (seo)

### ISSUE THREAD

**Issue by EliseAndresen** [stiftelsen-effekt/main-site#509]
Links have the passHref property but missing a tag. 

![Image](https://user-images.githubusercontent.com/112557835/199205570-fd41dad1-6c60-45af-a2d9-50f249eaed8e.png)

**Comment by EliseAndresen** [comment]
Looks like this is still an issue.

**Comment by adamalfredsson** [comment]
In Next 13, or by enabling an experimental option in Next 12.2, links render an anchor tag by default. There is a codemode tool that could help. https://nextjs.org/blog/next-13#nextlink
