### ISSUE TITLE
Implement changes for how we present information about GiveWell estimates on impact estimates

### ISSUE THREAD

**Issue by EliseAndresen** [stiftelsen-effekt/main-site#516]
[Design is available here](https://www.figma.com/file/rxgTB6O7vQZWbKDSoUY6EU/Min-Side?node-id=1397%3A3170)

Change the organisation information under each impact estimate to similar (but shorter)  to on the "topp lista" text about each org. Make the "estimert effekt" element expandable and move the text (about how this data is put together) that is now on each impact estimate here. 

Needs #510 and #511

**Comment by fellmirr** [comment]
This task was for design only.
