### ISSUE TITLE
Change layout on text below main header front page to reduce one line

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#554]
Would like it to be something like:
> Ikke alle bistandstiltak er like effektive. 
> Vi hjelper deg finne og støtte tiltakene 
> som hjelper verden mest mulig. 
> Helt gratis.

![Image](https://user-images.githubusercontent.com/12774906/206456200-f1721c52-cff1-4c46-9e42-844391204698.png)

**Comment by EliseAndresen** [comment]
Not sure how to best achieve this as the text is in sanity. Could you have a look when you have the time @fellmirr?
