### ISSUE TITLE
Rewording on FB-donation registration form to include Instagram

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#566]
Change header over form to: "Knytt din donasjon til din profil"
Change second field text to: "Betalings-ID fra Facebook eller Instagram"

![Image](https://user-images.githubusercontent.com/12774906/209099945-bd3e811b-437a-4a2d-b613-b1a93ea8e46c.png)

**Comment by EliseAndresen** [comment]
Find better title for menu. Could be Facebook og Instagram
