### ISSUE TITLE
Min side UI fixes

### ISSUE THREAD

**Issue by philiphand** [stiftelsen-effekt/main-site#568]

**Comment by philiphand** [comment]
- [ ] "Estimert effekt" text closes the dropdown menu when clicked


![Image](https://user-images.githubusercontent.com/44257880/210053164-f61038ea-57a2-4df9-9018-69a2a5614c24.png)


- [ ] Wrong pop-up is shown when cancelling Vipps agreement (it shows the one AvtaleGiro instead)

**Comment by fellmirr** [comment]
Covered by separate issues
