### ISSUE TITLE
[Feature]: Set up dev domain for Sweden

### ISSUE THREAD

**Issue by lorentzlasson** [stiftelsen-effekt/main-site#617]
### Description

I want to see a development version of the main site when visiting a dev url (e.g dev.geeffektivt.se). It may initially just point to what is on https://gieffektivt.no/, but will gradually transform into what the Swedish website is meant to be

### Anything else?

Questions: 
- how secret does it need to be? Will we need to hide it by anything other than obscurity?
- Can we get/do we need access to registrar for geeffektivt.se?

**Comment by lorentzlasson** [comment]
Have dev.geeffektivt.se registered on loopia. Just need something to point it to now

**Comment by adamalfredsson** [comment]
Added dev.geeffektivt.se CNAME record pointing at vercel
