### ISSUE TITLE
[Bug]: Excessive window event listeners

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#661]
### What happened?

Just stumbled upon this potential issue, but I believe many excessive event listeners should be observed on the window because the effect would run on every render and doesn't unsubscribe during effect cleanup.

https://github.com/stiftelsen-effekt/main-site/blob/6f880b8ed3bd716570a5ca55215b12009affdc79/components/shared/components/Widget/components/Widget.tsx#L45-L49

### Reproduction steps

1. Add a console.log at L46
2. Confirm that the effect runs many times

### What device are you seeing the problem on?

Mobile, Desktop

**Comment by fellmirr** [comment]
Yes, this looks like a nasty oversight!
The debounced callback mitigates some of the issue, but certainly it's not pretty. Great catch!

**Comment by fellmirr** [comment]
Adding an empty dependency array should do the trick, right?

**Comment by adamalfredsson** [comment]
> Adding an empty dependency array should do the trick, right?

Yes, or with the `debouncedScaleWidget` dependency. And maybe add a cleanup function to remove the event listener, but not as crucial I suppose!

**Comment by fellmirr** [comment]
Yes, even better :+1:

**Comment by fellmirr** [comment]
We fixed this, right @adamalfredsson ?
