### ISSUE TITLE
[Bug]: Auth0 invalid state

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#706]
### What happened?

![image](https://user-images.githubusercontent.com/25898698/235673033-f9abf69e-30db-40b0-ac15-17d3b78acbd4.png)

Seems like even when I'm already logged in, sometimes navigating to a profile page opens a new window prompting for authentication, at which it usually ends up in this "invalid state".

### Reproduction steps

1. Go to https://gieffektivt.no/
2. Navigate to min-side
3. A new login window opens
4. Authenticate with touch id
5. See "Invalid state"

However:

1. Go to https://gieffektivt.no/min-side
2. Login window opens in the same tab
3. Authenticate with touch id
4. No "Invalid state"

### What device are you seeing the problem on?

Desktop

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

**Comment by adamalfredsson** [comment]
Furthermore, I'm logged out after refreshing the page

**Comment by fellmirr** [comment]
This is an Arc quirk, we'll check back on this at a later stage
