### ISSUE TITLE
[Bug]: Missing date picker options

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#772]
### What happened?

Date picker is missing some days:

![image](https://github.com/stiftelsen-effekt/main-site/assets/25898698/faa7665c-d201-4307-9a2a-379ad6b60639)

### Reproduction steps

..

### What device are you seeing the problem on?

Mobile, Desktop

### What browsers are you seeing the problem on?

Chrome

**Comment by fellmirr** [comment]
This is by design :) Not all months have 31 days, and February is the shortest with 28th as the latest date.
