### ISSUE TITLE
[Bug]: Donor SSN is not prefilled by default

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#787]
### What happened?

When an authenticated donor makes a donation and applies for tax reduction, the ssn field is not prefilled with the donor's existing ssn.

### Reproduction steps

1. Login to /min-side
2. Open donation widget
3. Apply for tax deduction
4. SSN input field is displayed
5. SSN input field is empty 

### What device are you seeing the problem on?

Mobile, Desktop

**Comment by fellmirr** [comment]
For most donors, this should be checked and filled by default, since they have only one tax unit. We might even want to use the tax unit dropdown component when the donor is logged in (see the dropdown in the Agreement distribution section).
