### ISSUE TITLE
[Feature]: Add operations donations to new widget design 

### ISSUE THREAD

**Issue by EliseAndresen** [stiftelsen-effekt/main-site#810]
### Description

Operations should be a separate design/cause area, with extra space above. All cause areas with one org should only be single input field and no smart distribution. 

### Link to figma / design node

https://www.figma.com/file/RjsNExoNcft05GMnLGVUvD/Donation-Widget?type=design&node-id=10365%3A12931&mode=design&t=AKPbItABtVfILNtY-1

**Comment by fellmirr** [comment]
Right now it's ambiguous how to determine what is operations donations. Should we have this explicitly clear in the data model somehow? How do we solve this?

Kjør debatt!
