### ISSUE TITLE
Update logo to swedish version

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#855]
@EliseAndresen Do we have this? Could you send it over or whip it up? :)

**Comment by EliseAndresen** [comment]
Here are the ones for web:
![GeEffektivt_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/d6e3dacd-3c7f-4a1e-b109-32a89d1701d2)
![GiEffektivt_Logo_Hvit_RGB (2)](https://github.com/stiftelsen-effekt/main-site/assets/112557835/5474dc53-ba7b-4f87-9ad1-cc9d06d312f5)
![Ge_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/6a301deb-6522-4010-ae28-ce6d63532163)
![Ge_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/098d4b10-708e-49cc-aa5d-7f7b10461064)
![Ge_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/a261c467-6bba-4be3-aa7b-2f300f41dcab)
![Ge_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/b469fd50-1065-46e2-a417-e0a495ef0456)
![GeEffektivt_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/422e3af1-d7f4-4474-b99c-ee376807b0bf)
![GeEffektivt_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/22944bcf-6716-43ac-b4f3-1e2fd10e1f51)
![GeEffektivt_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/07812920-31ea-4e2b-8233-73c69ff5ed7f)

**Comment by EliseAndresen** [comment]
Version with coloured . is coming tomorrow

**Comment by EliseAndresen** [comment]
New logos with colour:

![Ge_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/4a134fc8-e2ae-46c6-a8e8-ecb72db4ebc1)
![Ge_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/6f48c6b8-3724-4e38-865b-394b1659898b)
![Ge_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/1daf9bcc-0382-45a9-b10c-2cd855ef89a1)
![Ge_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/9d3b9c8c-905b-47d5-8056-f601ec57ca7d)
![GeEffektivt_Logo_Hvit_CMYK](https://github.com/stiftelsen-effekt/main-site/assets/112557835/4ed45dae-262a-4c70-8dcf-02334abe3450)
![GeEffektivt_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/62b659b7-8a6e-4807-9894-89edf43ca02e)
![GeEffektivt_Logo_Hvit_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/5a864af0-7358-46a1-af10-ccc541e2d753)
![GeEffektivt_Logo_Sort_CMYK](https://github.com/stiftelsen-effekt/main-site/assets/112557835/036fe3df-28b9-4382-99da-6f4a6b509925)
![GeEffektivt_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/75034fe1-c52a-4911-ae99-efe2c291f077)
![GeEffektivt_Logo_Sort_RGB](https://github.com/stiftelsen-effekt/main-site/assets/112557835/bb4883b0-0373-4bc4-a758-8a175459137d)
