### ISSUE TITLE
[SEO] Change default SEO image to swedish logo for sweden

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#893]
@EliseAndresen Will help me :)

**Comment by EliseAndresen** [comment]
[Canva file](https://www.canva.com/design/DAF65x1L32A/bKsOVjgE-eJa2g0EBeEYpQ/edit?utm_content=DAF65x1L32A&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)



![Image](https://github.com/stiftelsen-effekt/main-site/assets/112557835/23e2518a-3676-4528-a1f5-ca9a9a0a9280)
