### ISSUE TITLE
Spørre Phillip om krav for vipps endring

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#92]

**Comment by fellmirr** [comment]
Jørgen nevnte at det er visse krav til utforming fra vipps når det kommer til endring av faste avtaler. Spørr @philiphand om hva disse er / hvor vi finner det.

**Comment by livejsa** [comment]
Fikk disse linkene:

https://github.com/vippsas/vipps-design-guidelines
https://github.com/vippsas/vipps-recurring-api

Men ikke rukket å se på de enda.

**Comment by philiphand** [comment]
Fant spesifikt disse avsnittene om det:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/44257880/159736210-35285c15-bb6f-4b3d-9672-4449f9b615b5.png">

Kilde: https://github.com/vippsas/vipps-recurring-api/blob/master/vipps-recurring-api.md#agreements
