### ISSUE TITLE
[Bug]: Articles page is bugging

### ISSUE THREAD

**Issue by SofieSjostrand** [stiftelsen-effekt/main-site#953]
### Contact Details

sofie@geeffektivt.se

### What happened?

Following issues: 
1. When publishing, it randomly starts showing unpublished articles on the website (see screenshot)
2. Ingress is present even when no ingress is added (see article about Arvid winning award)
3. When previewing, it leads to an inaccurate adress where artiklar is spelled artikler producing a 404
4. At times it seems to cache different versions for different people that won't update even though cache is cleared making it hard to see changes. 
![Skärmavbild 2024-04-03 kl  15 52 36](https://github.com/stiftelsen-effekt/main-site/assets/165918669/0166604f-e8ad-47e7-8e1b-92babfd5241d)

### Reproduction steps

1.
2.
3.
...

### What device are you seeing the problem on?

Desktop

### What browsers are you seeing the problem on?

Chrome

**Comment by fellmirr** [comment]
preview.page.ts in next api routes is the offender, it must check which environment it's in

**Comment by fellmirr** [comment]
I'm pushing a temp solution where we check the dataset when opening a preview. It would be better to actually query for the sub-path slug directly in sanity, but that update should be done when we get the new async function in Sanity v3:

https://www.sanity.io/docs/migrating-production-url-resolver

**Comment by SofieSjostrand** [comment]
I am sure this is good news but I have absolutely no idea what I just read :D

**Comment by fellmirr** [comment]
My bad, mostly a note to self! It's just to remember a technical detail from when we upgrade from Sanity 2 -> 3

I've now done the following:

- [x] Fixed opening preview for articles
- [x] Fixed missing logo on articles page
- [x] Fixed weird formatting for "teaser text" and re-enabled the "bigger" first article preview

When it comes to the cache issues it's a little hard to tell unless we have a concrete case to look at, will you let me know next time it happens?

I could also add that this page sucks a bit in general, it's hard to get a good overview and it doesn't really invite the reader to explore more (boring).

But articles are mostly getting traffic from social media AFAIK, so we have not prioritised doing anything here in the near future (other than fixing obvious bugs of course, very helpful when those are reported!)

Anything in this issue that remains, or am I okay to close this?
