### ISSUE TITLE
[Bug]: Wealth calculator doesn't work (SE)

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#975]
### What happened?

When submitting your salary, it keeps on loading indefinitely without any results.

### Reproduction steps

1. https://geeffektivt.se/hur-rik-ar-du
2. Enter salary
3. Nothing happens!

### What device are you seeing the problem on?

Mobile, Desktop

### Relevant log output

```shell
XHR request to:
https://corsproxy.io/?https://app.skatteverket.se/rakna-skatt-client-skut-skatteutrakning/api/skatteberakning-fysisk/rakna-ut-skatt

Response:
> Förfrågan blockerad!
> Den efterfrågade webbsidan nekades. Vänligen kontakta er administratör.
> Ert support ID är: 876946491217251350
```

**Comment by fellmirr** [comment]
Probably should just do this on build time. Fixed temporarily for now, but need to revisit this soon.

https://github.com/stiftelsen-effekt/main-site/issues/977
