### ISSUE TITLE
[Feature]: Lage ny graf for dødsfall per aldersgruppe til bruk i slide deck

### ISSUE THREAD

**Issue by karirk** [stiftelsen-effekt/main-site#983]
### Description

Se kommentarer i selve slide dekket: https://docs.google.com/presentation/d/1I6hRnXt0ODqhbFZClWjrv382tD-WEL8ETsr8r80wXw4/edit#slide=id.g278d5199526_0_42

**Comment by fellmirr** [comment]
Moved to Asana
